### ISSUE TITLE
Invalid archive returned with version 10.27.0

### ISSUE THREAD

**Issue by michal-zampach** [akaffenberger/firebase-ios-sdk-xcframeworks#81]
I'm having following issue with latest version `10.27.0`. I tried example workspace with same result.

> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseABTesting.xcframework.zip' which is required by binary target '_FirebaseABTesting'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FBLPromises.xcframework.zip' which is required by binary target '_FBLPromises'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseAnalytics.xcframework.zip' which is required by binary target '_FirebaseAnalytics'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseAppCheck.xcframework.zip' which is required by binary target '_FirebaseAppCheck'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_AppAuth.xcframework.zip' which is required by binary target '_AppAuth'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_AppCheckCore.xcframework.zip' which is required by binary target '_AppCheckCore'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseAppCheckInterop.xcframework.zip' which is required by binary target '_FirebaseAppCheckInterop'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseAnalyticsOnDeviceConversion.xcframework.zip' which is required by binary target '_FirebaseAnalyticsOnDeviceConversion'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseAppDistribution.xcframework.zip' which is required by binary target '_FirebaseAppDistribution'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseAuth.xcframework.zip' which is required by binary target '_FirebaseAuth'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseAuthInterop.xcframework.zip' which is required by binary target '_FirebaseAuthInterop'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseCore.xcframework.zip' which is required by binary target '_FirebaseCore'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseCoreExtension.xcframework.zip' which is required by binary target '_FirebaseCoreExtension'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseCoreInternal.xcframework.zip' which is required by binary target '_FirebaseCoreInternal'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseCrashlytics.xcframework.zip' which is required by binary target '_FirebaseCrashlytics'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseDatabase.xcframework.zip' which is required by binary target '_FirebaseDatabase'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseDynamicLinks.xcframework.zip' which is required by binary target '_FirebaseDynamicLinks'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseFirestore.xcframework.zip' which is required by binary target '_FirebaseFirestore'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseFirestoreInternal.xcframework.zip' which is required by binary target '_FirebaseFirestoreInternal'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseFunctions.xcframework.zip' which is required by binary target '_FirebaseFunctions'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseInAppMessaging.xcframework.zip' which is required by binary target '_FirebaseInAppMessaging'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseInstallations.xcframework.zip' which is required by binary target '_FirebaseInstallations'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseMLModelDownloader.xcframework.zip' which is required by binary target '_FirebaseMLModelDownloader'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseMessaging.xcframework.zip' which is required by binary target '_FirebaseMessaging'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseMessagingInterop.xcframework.zip' which is required by binary target '_FirebaseMessagingInterop'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebasePerformance.xcframework.zip' which is required by binary target '_FirebasePerformance'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseRemoteConfig.xcframework.zip' which is required by binary target '_FirebaseRemoteConfig'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseRemoteConfigInterop.xcframework.zip' which is required by binary target '_FirebaseRemoteConfigInterop'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseSessions.xcframework.zip' which is required by binary target '_FirebaseSessions'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseSharedSwift.xcframework.zip' which is required by binary target '_FirebaseSharedSwift'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_FirebaseStorage.xcframework.zip' which is required by binary target '_FirebaseStorage'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GTMAppAuth.xcframework.zip' which is required by binary target '_GTMAppAuth'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GTMSessionFetcher.xcframework.zip' which is required by binary target '_GTMSessionFetcher'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GoogleAppMeasurement.xcframework.zip' which is required by binary target '_GoogleAppMeasurement'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GoogleAppMeasurementIdentitySupport.xcframework.zip' which is required by binary target '_GoogleAppMeasurementIdentitySupport'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GoogleAppMeasurementOnDeviceConversion.xcframework.zip' which is required by binary target '_GoogleAppMeasurementOnDeviceConversion'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GoogleDataTransport.xcframework.zip' which is required by binary target '_GoogleDataTransport'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GoogleMobileAds.xcframework.zip' which is required by binary target '_GoogleMobileAds'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GoogleSignIn.xcframework.zip' which is required by binary target '_GoogleSignIn'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_GoogleUtilities.xcframework.zip' which is required by binary target '_GoogleUtilities'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_Promises.xcframework.zip' which is required by binary target '_Promises'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_RecaptchaInterop.xcframework.zip' which is required by binary target '_RecaptchaInterop'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_UserMessagingPlatform.xcframework.zip' which is required by binary target '_UserMessagingPlatform'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_absl.xcframework.zip' which is required by binary target '_absl'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_grpc.xcframework.zip' which is required by binary target '_grpc'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_grpcpp.xcframework.zip' which is required by binary target '_grpcpp'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_leveldb.xcframework.zip' which is required by binary target '_leveldb'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_nanopb.xcframework.zip' which is required by binary target '_nanopb'
> 
> invalid archive returned from 'https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/releases/download/10.27.0/_openssl_grpc.xcframework.zip' which is required by binary target '_openssl_grpc'
>

**Comment by daniapopov** [comment]
I believe this issue would also be fixed by my PR:
https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/pull/83

**Comment by michal-zampach** [comment]
I tried to use updated `package.sh` script but the issue is still the same.
